name: Secrets
# Run this workflow every time a new commit pushed to your repository.
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  
    fetch_aws_dynamic_secrets:
          runs-on: ubuntu-latest
          name: Fetch AWS dynamic secrets
          #---------Required---------#
          permissions: # Must change the job token permissions to use JWT auth
            id-token: write
            contents: read
          #--------------------------#       
          steps:
          - name: Fetch dynamic secrets from AKeyless
            id: fetch-dynamic-secrets
            uses: LanceMcCarthy/akeyless-action@v3
            with:
              access-id: ${{ secrets.AKEYLESS_ACCESS_ID }} # Looks like p-fq3afjjxv839
              dynamic-secrets: '{"/AWS/aws_user":"aws_dynamic_secrets"}'
              
      # **** KEY TAKEAWAY - EXPORT DYNAMIC SECRET's KEYS TO ENV VARS *****
          - name: Export Secrets to Environment
            run: |
              echo '${{ steps.fetch-dynamic-secrets.outputs.aws_dynamic_secrets }}' | jq -r 'to_entries|map("AWS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      
      # You can now access each secret separately as environment variables
          - name: Verify Vars
            run: |
              echo "access_key_id: ${{ env.AWS_access_key_id }}"
              echo "id: ${{ env.AWS_id }}"
              echo "secret_access_key: ${{ env.AWS_secret_access_key }}"
              echo "security_token: ${{ env.AWS_security_token }}"
              echo "ttl_in_minutes: ${{ env.AWS_ttl_in_minutes }}"
              echo "type: ${{ env.AWS_type }}"
              echo "user: ${{ env.AWS_user }}"

              export AWS_ACCESS_KEY_ID="${{ env.AWS_access_key_id }}"
              export AWS_SECRET_ACCESS_KEY="${{ env.AWS_secret_access_key }}"

          - name: Verify Vars

            run: |


    # terraform:
    #     runs-on: ubuntu-latest
    #     needs: fetch_aws_dynamic_secrets # This ensures the fetch_aws_dynamic_secrets job runs first


        # steps:
        #   - uses: actions/checkout@v2
      
        #   - name: Setup Terraform
        #     uses: hashicorp/setup-terraform@v2

          - name: Terraform Init
            uses: hashicorp/setup-terraform@v2
            # env: 
            # run: |
            #   env:
            #     AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
            #   echo "dynamic_secret_values: ${{steps.fetch-dynamic-secrets.outputs.aws_dynamic_secrets }}"

            #   echo "access_key_id:  ${{ needs.fetch-dynamic-secrets.outputs.access_key_id }}"
            #   echo "secret_access_key: ${{needs.fetch-dynamic-secrets.outputs.secret_access_key }}"

            #   export AWS_ACCESS_KEY_ID=${{needs.fetch-dynamic-secrets.outputs.access_key_id }}
            #   export AWS_SECRET_ACCESS_KEY=${{ needs.fetch-dynamic-secrets.outputs.secret_access_key }}

      
            #   terraform init
            env:
              AWS_ACCESS_KEY_ID: ${{ env.AWS_access_key_id }}
              AWS_SECRET_ACCESS_KEY: ${{ env.AWS_secret_access_key }}

      
          - name: Terraform Plan
            uses: hashicorp/setup-terraform@v2

            # run: |
            #   export AWS_ACCESS_KEY_ID= ${{ env.AWS_access_key_id }}
            #   export AWS_SECRET_ACCESS_KEY= ${{ env.AWS_secret_access_key }}

      
            #   terraform plan 
            env:
              AWS_ACCESS_KEY_ID: ${{ env.AWS_access_key_id }}
              AWS_SECRET_ACCESS_KEY: ${{ env.AWS_secret_access_key }}
                
          - name: Terraform Apply
            uses: hashicorp/setup-terraform@v2

            # run: |
            #   export AWS_ACCESS_KEY_ID=${{ env.AWS_access_key_id }}
            #   export AWS_SECRET_ACCESS_KEY=${{ env.AWS_secret_access_key }}
      
            #   terraform apply
            env:
              AWS_ACCESS_KEY_ID: ${{ env.AWS_access_key_id }}
              AWS_SECRET_ACCESS_KEY: ${{ env.AWS_secret_access_key }}

    